default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: tasklist_development

test:
  <<: *default
  database: tasklist_test

production:
  <<: *default
  database: tasklist_production
  username: tasklist
  password: <%= ENV['TASKLIST_DATABASE_PASSWORD'] %>
